### ISSUE TITLE
Error WP Core 6.4: Lodash js dependency error.

### ISSUE THREAD

**Issue by rahulsprajapati** [humanmade/publication-checklist#26]
Getting error with publication checklist on WP Core 6.4, when publishing post with checklist

<img width="1000" alt="image" src="https://github.com/humanmade/publication-checklist/assets/10358350/1a932d7e-40ef-41e5-b1b5-de63262e5132">

```
Dt<@https://local-wp.test/wp-content/plugins/publication-checklist/build/index.js?ver=6.4.1:12:21485
Ze/</</n<@https://local-wp.test/wp-includes/js/dist/data.min.js?ver=dc5f255634f3da29c8d5:9:3088
ze/</l/l<@https://local-wp.test/wp-includes/js/dist/data.min.js?ver=dc5f255634f3da29c8d5:9:1958
__unstableMarkListeningStores@https://local-wp.test/wp-includes/js/dist/data.min.js?ver=dc5f255634f3da29c8d5:2:22508
Oe/a</<@https://local-wp.test/wp-includes/js/dist/data.min.js?ver=dc5f255634f3da29c8d5:2:22765
l@https://local-wp.test/wp-includes/js/dist/data.min.js?ver=dc5f255634f3da29c8d5:9:1922
ze/<@https://local-wp.test/wp-includes/js/dist/data.min.js?ver=dc5f255634f3da29c8d5:9:2426
Je@https://local-wp.test/wp-includes/js/dist/data.min.js?ver=dc5f255634f3da29c8d5:9:2637
Qe@https://local-wp.test/wp-includes/js/dist/data.min.js?ver=dc5f255634f3da29c8d5:9:2953
Ze/</<@https://local-wp.test/wp-includes/js/dist/data.min.js?ver=dc5f255634f3da29c8d5:9:3078
wt@https://local-wp.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:47637
js@https://local-wp.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:120584
wl@https://local-wp.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:88661
bl@https://local-wp.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:88589
yl@https://local-wp.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:88450
il@https://local-wp.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:85274
fl@https://local-wp.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:85661
Nn@https://local-wp.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:32474
n/ul/<@https://local-wp.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:83226
```

Looks like this error is because of Lodash lib removed from WP 6.4, 

ref: https://github.com/WordPress/gutenberg/pull/52571
https://make.wordpress.org/core/2023/10/17/miscellaneous-editor-changes-in-wordpress-6-4/#comment-45787

But this is not completely removed it is still registered, but it is no longer enqueued by default. ref: https://github.com/WordPress/wordpress-develop/blob/6.4/src/wp-includes/script-loader.php#L113

This is being used at: https://github.com/humanmade/publication-checklist/blob/182861525911d6a7dd7a879be743f74809834588/src/components/ConfirmOverrideHelpText.js#L1

But not added as dependency when registered build script of publication-checklist.

https://github.com/humanmade/publication-checklist/blob/182861525911d6a7dd7a879be743f74809834588/inc/namespace.php#L64-L72

**Comment by svandragt** [comment]
Thanks just encountered this.
