### ISSUE TITLE
Share a list of already available checks

### ISSUE THREAD

**Issue by Mte90** [humanmade/publication-checklist#3]
It is a framework so share snippets or other example can be interesting to speed up the adoption, like CMB2 did.

**Comment by LukaszJaro** [comment]
Good idea, I was looking over the readme and I don't even understand how to use it, this is not as dev friendly as CMB2 :(

**Comment by elvismdev** [comment]
+1 Can we see a simple example, like how to require the core `post_title` field from Gutenberg? That'd be great to start with!

**Comment by neverything** [comment]
Here is an easy to use example:

```php
<?php
use function Altis\Workflow\PublicationChecklist\register_prepublish_check;
use Altis\Workflow\PublicationChecklist\Status;

add_action( 'altis.publication-checklist.register_prepublish_checks', function() {
    register_prepublish_check(
        'title_length',
        array(
            'run_check' => function ( array $post, array $meta ): Status {
                if ( strlen( $post['post_title'] ) <= 80 ) {
                    return new Status( Status::INCOMPLETE, 'Post title is too short' );
                }
                return new Status( Status::COMPLETE, 'Title long enough' );
            },
        )
    );
} );
```

**Comment by LukaszJaro** [comment]
That's cool!, thanks. It works, I downloaded the latest release and put the code above in a must use plugin to test quickly. 

Noticed it's not asynchronous with the checks, only fires the checks when you hit preview/publish button or on page load. Probably can be solved by using the WP REST API.

**Comment by roborourke** [comment]
There's an example on the README now as well as other docs regarding block editor integration and filters etc..., we could collect user submitted examples in the wiki in future but I don't think we'll be doing much more than that right now.

Regarding the async/sync checking this is a trade-off between ensuring any server side actions / filters have been run before determining what the final saved data is. We're aware that's not the best UX though, any further discussion on that topic can go in #9 

Thanks @neverything for posting the example!
