### ISSUE TITLE
Tried this in regular ol' WordPress, checklist of all checks doesn't show.

### ISSUE THREAD

**Issue by elvismdev** [humanmade/publication-checklist#4]
Hi, I pulled the plugin into my `wp-content/plugins` directory, run `composer install` and after `yarn install && yarn build`. 

Then I added into a `mu-plugin` file:

```php
use function Altis\Workflow\PublicationChecklist\register_prepublish_check;
use Altis\Workflow\PublicationChecklist\Status;

add_action( 'altis.publication-checklist.register_prepublish_checks', function () {
	register_prepublish_check( 'external_date', [
		'run_check' => function ( array $post, array $meta ) : Status {

			if ( isset( $meta['external_date'] ) ) {
				return new Status( Status::COMPLETE, 'External Date completed' );
			}

			return new Status( Status::INCOMPLETE, 'Missing External Date data' );
		},
	] );
} );


add_filter( 'altis.publication-checklist.block_on_failing', '__return_true' );
```

I was expecting to see the simple checklist of all checks that Publication Checklist would render by default ([like the one from this Tweet?](https://twitter.com/rmccue/status/1173550662296190976/photo/1)), but nothing come up on my end.

![2019-11-19_23-55](https://user-images.githubusercontent.com/3847077/69219945-c8949700-0b28-11ea-8dcc-651b01f01c39.png)

What I'm missing from the docs to make this work on a regular WordPress + Gutenberg installation?

**Comment by ntwb** [comment]
![image](https://user-images.githubusercontent.com/1016458/69385566-e2de9880-0d13-11ea-97b3-3e44f1fda52c.png)

Click the ✅

**Comment by Mahjouba91** [comment]
Hello @elvismdev, I have the same issue, I have installed the plugin through composer (bedrock), activated it on the backend, copy paste the snippet code on functions.php of the theme, and I don't see anything on the backend (I don't see the check icon on red in your screenshot), all articles get published without any test.

I am running last WP version (5.3).

Did I miss something ? It would be great to have a proper Installation documentation on the repo.

Thanks for your help.

**Comment by Mahjouba91** [comment]
Any idea ? @ntwb @rmccue 

Could you please confirm that the framework works with last WordPress and Gutenberg versions please ?

**Comment by rmccue** [comment]
Apologies, I totally missed this issue somehow! Publication Checklist definitely works with latest WordPress and Gutenberg.

If you inspect the "Publish" button in that overlay, you should see this in the DOM:

<img width="636" alt="Screen Shot 2019-12-04 at 13 50 17" src="https://user-images.githubusercontent.com/21655/70147870-07842a00-169d-11ea-9b58-706309efaf25.png">

(We replace the publish button with our own to control it better.)

If you're not seeing that, the JS hasn't loaded properly. If you are seeing that, let me know, as there's some other issue occurring.

**Comment by elvismdev** [comment]
@ntwb @rmccue @Mahjouba91 Thank you all for the input. I will soon get back to this in the project i'm trying to use Publication Checklist and will report back with my findings.

**Comment by rmccue** [comment]
Closing out; feel free to reopen or comment further if needed.

**Comment by Mahjouba91** [comment]
Hello @rmccue,

After your comment, I had a look at the DOM, and I can see your custom component for the publish button. Otherwise, I still don't see any action when I click the publish button, it publishes directly the post without blocking anything.
